'use client'

import { SpeedInsights } from "@vercel/speed-insights/next"
// import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { useEffect } from 'react';
import { initSensitiveFilter } from '@/app/utils/sensitiveWords';
import { Toaster } from 'sonner';
import { Providers } from "@/components/layout/ThemeProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  useEffect(() => {
    // 应用启动时初始化敏感词过滤器
    initSensitiveFilter();
  }, []);

  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} bg-background text-foreground`}>
          <Providers
          >
            {children}
            <Toaster />
            <SpeedInsights />
          </Providers>
      </body>
    </html>
  );
}
